[project]
name = "powermean-mcts-alphazero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numba>=0.62.1",
    "numpy>=2.3.3",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
